default: &default
    host: localhost
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: deployuser
    password: deployment

development:
  <<: *default
  database: arenbnb_new_dev

test:
  <<: *default
  database: arenbnb_new_test

production:
  <<: *default
  database: arenbnb_new_prod
