default: &default
    host: localhost
    adapter: postgresql
    username: postgres
    password: postgres
    encoding: unicode
    pool: 5

development:
  <<: *default
  database: arenbnb_new_dev

test:
  <<: *default
  database: arenbnb_new_test

production:
  <<: *default
  database: arenbnb_new_prod

staging:
  <<: *default
  database: arenbnb_new_staging
